apiVersion: apps/v1
kind: Deployment
metadata:
  name: dj-deploy
  namespace: edu-clever-yalow
spec:
  replicas: 1
  selector:
    matchLabels:
      project: dj
  template:
    metadata:
      labels:
        project: dj
    spec:
      containers:
      - name: dj-container
        image: zapivahin/zmg_django:firsttry
        envFrom:
        - configMapRef:
            name: django-config
        - secretRef:
            name: postgres
        ports:
          - containerPort: 80
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dj-service
spec:
  selector:
    project: dj
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30311
