version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: test_k8s
      POSTGRES_USER: test_k8s
      POSTGRES_PASSWORD: OwOtBep9Frut
    ports:
      - 192.168.1.103:5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local