apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 60
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: django-migrate-app
        image: django_app
        imagePullPolicy: Never
        command: ["python", "manage.py",  "migrate", "--no-input"]
        envFrom:
          - configMapRef:
              name: django-config
